title: Patrick Tchicali
logo: /images/profile_pic.jpg
description: I am a graduate student and member of Shouno Laboratory, at The University of Electro-communications, (UEC) Tokyo. I started in spring of 2019 after completing my Bachelors in Informatics and Computer Science at the same university. I am currently studying ML, and Bayesian Statistics.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
