title: Patrick Tchicali
logo: /images/profile_pic.jpg
description: Member of Shouno Laboratory. I am currently interested in Machine learning and Bayesian statistics. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
